// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ULDS","status":true,"description":"无限图层(经过修改，不具备通用性)","parameters":{"Default Path":"parallaxes","Default Z":"0.5"}},
{"name":"Community_Lighting_MZ","status":true,"description":"v4.6 Creates an extra layer that darkens a map and adds lightsources! Released under the MIT license!","parameters":{"---General Settings---":"","Options Menu Entry":"Lighting Effects","Light event required":"false","Shift lights with events":"false","Reset Lights":"false","Kill Switch":"None","Kill Switch Auto":"false","Note Tag Key":"cl","---DayNight Settings---":"","Daynight Initial Speed":"10","Save DaynightHours":"0","Save DaynightMinutes":"0","Save DaynightSeconds":"0","Save Night Switch":"0","No Autoshadow During Night":"false","Night Hours":"0, 1, 2, 3, 4, 5, 6, 19, 20, 21, 22, 23","DayNight Colors":"[\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#9999ff\",\"#ccccff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffcc88\",\"#9999ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\"]","Daynight Initial Hour":"0","---Offset and Sizes---":"","Lights Active Radius":"0","Player radius":"300","Flashlight offset":"0","Flashlight X offset":"0","Screensize X":"1024","Screensize Y":"720","Lightmask Padding":"32","---Battle Settings---":"","Battle Tinting":"true","Light Mask Position":"Above"}},
{"name":"UTA_MessageSkip","status":true,"description":"Skip message on pressing a particular key.","parameters":{"Skip Key":"control","Show Trace":"false"}},
{"name":"Galv_ScreenZoom","status":true,"description":"用于放大画面(经过修改)","parameters":{"Battle Zoom":"1"}},
{"name":"MrTS_EventNames","status":true,"description":"用于靠近时显示浮动图标(经过修改，不具备通用性)","parameters":{"Default Range":"5","Font Size":"24","Font Name":"GameFont","Fade":"True","Fade Timer":"30"}},
{"name":"GALV_ActionIndicatorsMZ","status":true,"description":"用于显示事件上的浮动图标(经过修改，不具备通用性)","parameters":{"yOffset":"-10","zPosition":"5","autoHide":"true","iconOpacity":"210"}},
{"name":"Tool","status":true,"description":"","parameters":{}}
];
